server:
  port: ${PORT}
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: "jdbc:postgresql://localhost:${HOST}/${POSTGRES_DB}"
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
jwt:
  signerKey: "+Z4hcdtnDWWbSKelvfZ8vz4s55Y8nPZESY1/is2UgYBBFHE4oRCs+daKEY5TNZ/q"
  valid-duration: 3600 # in second
  refreshable-duration: 360000 # seconds