services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
#      - rabbitmq
      - elasticsearch
#      - redis

  db:
    image: postgres:16.3
    env_file:
      - .env
    ports:
      - "5432:5432"

#  rabbitmq:
#    image: rabbitmq:management
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"  # AMQP port
#      - "15672:15672"  # Management UI port
#    env_file:
#      - .env
#    volumes:
#      - rabbitmq_data:/var/lib/rabbitmq

  elasticsearch:
    image: elasticsearch:8.15.3
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
        memlock:
            soft: -1
            hard: -1
    ports:
      - "9200:9200"

#  redis:
#    image: redis:latest
#    container_name: redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data

