services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
#      - rabbitmq
      - elasticsearch
#      - redis
    restart: always

  db:
    image: postgres:16.3
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  #  rabbitmq:
#    image: rabbitmq:management
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"  # AMQP port
#      - "15672:15672"  # Management UI port
#    env_file:
#      - .env
#    volumes:
#      - rabbitmq_data:/var/lib/rabbitmq

  elasticsearch:
    image: elasticsearch:8.15.3
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    restart: always
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
#  redis:
#    image: redis:latest
#    container_name: redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data

volumes:
  postgres_data:
  elastic_data:


